# Generated by Django 4.1.1 on 2022-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcartlinemainmodel',
            name='status',
            field=models.CharField(choices=[('CART', 'CART'), ('WISHLIST', 'WISHLIST')], max_length=10),
        ),
    ]
