# Generated by Django 4.0.6 on 2022-09-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Order ID')),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Cancel', 'Cancel'), ('pending', 'PENDING'), ('out_for_delivery', 'OUT FOR DELIVERY'), ('delivered', 'DELIVERED')], default='pending', max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('lines', models.ManyToManyField(related_name='orderOrderModel_lines', to='cart.cartcartlinemainmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderOrderModel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
