# Generated by Django 4.1.1 on 2022-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderordermodel',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'CANCEL'), ('PENDING', 'PENDING'), ('OUT_OF_DELIVERY', 'OUT_OF_DELIVERY'), ('DELIVERED', 'DELIVERED')], default='pending', max_length=16),
        ),
    ]
